<H1>Firma budowlana Lasota</H1>

<img id="aboutImg" src="<?php echo $this->baseUrl();?>/public/images/about.jpg" alt="budynek"></img>
<p>
Firma budowlana KOS zajmuje się wykonawstwem obiektów budowlanych, remontami, adaptacjami i modernizacjami budowli. Głównym obszarem świadczenia naszych usług są województwa : mazowieckie oraz świętokrzyskie.
 </p>
 <p>
  
Nasza firma ma charakter rodzinny oraz wieloletnie tradycje budowlane. Trzon przedsiębiorstwa stanowi odpowiednio dobrana i sprawdzona na budowach krajowych i zagranicznych kadra o bogatym dorobku zawodowym.

   </p> 
   
   <p>
Zatrudniamy jedynie wyspecjalizowanych pracowników przez co przygotowani jesteśmy do prowadzenia większości robót w branży budowlanej.
   </p>
   
   <p>
   
Świadczymy usługi budowlane zarówno jako generalny wykonawca jak i podwykonawca.
</p>