<div id="text">
<h1>Strona Gówna</h1>

<p>
		Witamy Państwa na stronie naszej firmy.
Zapraszamy serdecznie do zapoznania się z naszą oferta internetowej
oraz owocnej wspópracy przy wykonaniu wszelkich instalacji.
</p>
<p>
Instalacje grzewcze, instalacje sanitarne, instalacje elektryczne, ochrona mienia,  
wentylacja i klimatyzacja, technika oświetleniowa, inne instalacje, to wszystko mamy
Państwu do zaoferowania jako profesjonalni wykonawcy.
</p>
</div>