<h1>Solary</h1>
Energia słoneczna to ogromny potencjał energetyczny, który dała nam natura.

   Biorąc pod uwagę ciągle rosnące ceny paliw i energii,
    zainwestowanie w instalację kolektorów słonecznych będzie <strong>udaną inwestycją w przyszłość</strong>.

W każdym gospodarstwie domowym, zapotrzebowanie na ciepłą wodę użytkową jest relatywnie stałe.
 Zastosowanie instalacji solarnej C.W.U.   pozwala <strong>zaoszczędzić do 70% energii </strong>  rocznie potrzebnej do podgrzania,
  a w okresie letnim do 100% co może oznaczać ,że nie musimy uruchamiać kotła grzewczego lub włączać grzałki.

Warto pomyśleć o instalacji solarnej już na etapie budowy domu,
 gdyż koszt takiej instalacji robi się o wiele niższy  niż w przypadku budynku 
  już użytkowanego . Zazwyczaj w każdym nowym budynku stosowane są termy elektryczne lub gazowe.
   Zamiast  tego, lepiej już na wstępie zainwestować w zasobnik solarny dwu wężownicowy , do którego w dowolnej chwili można zamontować kolektory słoneczne. Stanowi to około 35-50%  kosztów zamontowania nowej instalacji.
