<h2>Kompletne rozwiązania systemów grzewczych</h2>
<p>
Tradycyjne wkłady kominkowe wykonane z najwyższej jakości żeliwa w polskiej odlewni.
 Trwałe materiały, prosta konstrukcja i solidne wykonanie. 
 Powietrzne wkłady kominkowe to doskonałe rozwiązanie dla tych, którzy chcą cieszyć się widokiem ognia w jesienne zimowe wieczory,
 mając jednocześnie zapewnione podstawowe źródło ciepła w postaci kotła lub pompy ciepła.
 Nasze wkłady mogą być zastosowane również w systemie ogrzewania z wykorzystaniem dystrybucji gorącego powietrza.
 Tradycyjna konstrukcja wkładu żeliwnego została uzupełniona o nowoczesny system sterowania „NeoARIA”.
 Umożliwia on automatyczną regulację procesu spalania poprzez sterowanie ilością powietrza do spalania.

</p>
