
<?php	

	 if (count($this->paginator)): 
 
		$t = $this->paginator->getItem(0,1);
	
	echo '<ul id="Menu">';	
	
 foreach ($this->paginator as $item):  	

 
     echo '<li>';
     
   
     
          echo  '<div id="tresc">';

        
		foreach ( $this->keysAndLabels as $key => $label ) {

			
			 echo '<tr> <td><a class="preview" href="'. $this->url( array( 'module' => $this->module,
			 
													'controller' => $this->escape($this->controler),
			 
													'action' => $this->escape($this->action),
			 
													'id' => $this->escape($item['id'] ) ) )
          					
								.'">'.$this->escape($item [ $key ]).'</a></tr> </td>';				
	 	}
	    	
            
	
		 echo "</div>";
		 
	
	 
	 echo"</li>";
	 	 
  	endforeach;
  
	echo "</ul>";
	
 
 endif;

 echo $this->paginationControl($this->paginator,

                                    'Jumping',

                                    'my_pagination_control.phtml',  array("route" => array("module" => $this->module, "controller" => $this->controller, ) ) ); 

?>